runtime: python38

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  creds: "serviceAccCreds.json"
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
  secure: always